### ISSUE TITLE
What is `_layouts` directory?

### ISSUE THREAD

**Issue by anothertempore** [pmadruga/myUI#2]
Hi,

I want to know what `_layouts` directory does, but I didn't find answer. Could you please tell me why we need this directory, and what's the different with `docs` directory?

Thanks for helping!

**Comment by alexkvazos** [comment]
@Kexin-Li  Ever found out?

**Comment by anothertempore** [comment]
Is that jekyll needs?

**Comment by pmadruga** [comment]
Yes, it's from jekyll, @Kexin-Li .
